version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Building the application"
      - # Add any build commands here, like tests, etc.

  post_build:
    commands:
      - echo "Running deploy script"
      - chmod +x deploy.sh
      - ./deploy.sh

artifacts:
  files:
    - '**/*'
  discard-paths: yes
